name: Run Java programs
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'epi_judge_cpp*/**'
      - 'epi_judge_python*/**'
      - 'html/**'
      - '.gitignore'
      - 'index.html'
      - '*.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move page
        run: |
          mkdir public
          mv html index.html problem_mapping.js public/ 
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
